### ISSUE TITLE
inspectr is slow when the number of runs is more than ~300-400

### ISSUE THREAD

**Issue by astafan8** [toolsforexperiments/plottr#10]
Users report that loading a `.db` file into `inspectr` takes ~seconds when the number of runs in the database is ~300-400. When the number of runs in ~1000, it takes ~2 minutes.

It should be easy to improve this via smarted SQL requests.

**Comment by wpfff** [comment]
this is solved in the new plottr version. There we only load details about each run on-demand, which performs much better.
