### ISSUE TITLE
MatplotlibDeprecationWarning: Passing non-integers as three-element position specification

### ISSUE THREAD

**Issue by astafan8** [toolsforexperiments/plottr#136]
> c:\code\plottr\plottr\plot\mpl.py:477: MatplotlibDeprecationWarning: Passing non-integers as three-element position specification is deprecated since 3.3 and will be removed two minor releases later.

`self.axes.append(self.fig.add_subplot(nrows, ncols, i))`

**Comment by jenshnielsen** [comment]
I belive this has already been fixed by https://github.com/toolsforexperiments/plottr/commit/35e9fe5b80ee76e6ccb1b47e25ac9c6f90106f6c as part of https://github.com/toolsforexperiments/plottr/pull/121
