### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by zznature** [toolsforexperiments/plottr#141]
Hello, new here. I run into the sqlite3.OperationalError when running plottr. It may not open the database file and could not realize live plotting. How could I make it work?
Thanks!
@wpfff 

File "c:\users\zhouz\anaconda3\lib\site-packages\qcodes\dataset\sqlite\database.py", line 136, in connect
    sqlite3_conn = sqlite3.connect(name, detect_types=sqlite3.PARSE_DECLTYPES,
sqlite3.OperationalError: unable to open database file

![Untitled](https://user-images.githubusercontent.com/11894344/96733474-132f2b00-13ec-11eb-9b20-bf653e94a464.png)
![image](https://user-images.githubusercontent.com/11894344/96733824-7751ef00-13ec-11eb-95a2-9501c7a13a04.png)

**Comment by astafan8** [comment]
hey @zznature , what versions of plottr and qcodes are you using? are you using conda for environment management or something else? and what operation system?

**Comment by wpfff** [comment]
Does the file you're trying to open work fine when you retrieve data using
the qcodes tools directly?

**Comment by zznature** [comment]
I could plot the figures using qcodes tools, so I suppose the database file works fine. Example DAQ and plot as follows
![image](https://user-images.githubusercontent.com/11894344/96950300-8cc63680-151c-11eb-8067-a10e7e01b0dc.png)

The version of plottr is 0.2.0 (the latest release). I am using conda for environment management on a Windows 10 laptop.

Thanks!

**Comment by astafan8** [comment]
@zznature a few releases of plottr has been published since this issue was files - is plottr working correctly now, has this problem occurred again?

**Comment by wpfff** [comment]
this seems to be inactive. i'm closing it.
