### ISSUE TITLE
plottr throws warning for complex data

### ISSUE THREAD

**Issue by FarBo** [toolsforexperiments/plottr#178]
The warning is something like this:
py.warnings ¦ _showwarnmsg ¦ \plottr\plottr\plot\mpl.py:877: ComplexWarning: Casting complex values to real discards the imaginary part

If a dataset has complex values, plottr terminal throws these kinds of warning messages when plottr loads that dataset for plotting. It is not a big issue, but it would be nice to somehow handle that.

**Comment by wpfff** [comment]
this is actually fixed already...
