### ISSUE TITLE
Numpy error while using Plottr for live plotting with Numpy version 1.20.3

### ISSUE THREAD

**Issue by Akshita07** [toolsforexperiments/plottr#196]
Following error is seen while using Plottr for live plotting qcodes measurements (numpy version 1.20.3 in the environment):

```python
Traceback (most recent call last):
  File "c:\users\v-singak\documents\projects\plottr\plottr\plottr\plot\base.py", line 108, in setData
    self.plotWidget.setData(self.data)
  File "c:\users\v-singak\documents\projects\plottr\plottr\plottr\plot\mpl.py", line 949, in setData
    self._plotData(adjustSize=True)
  File "c:\users\v-singak\documents\projects\plottr\plottr\plottr\plot\mpl.py", line 1032, in _plotData
    self._colorplot2d()
  File "c:\users\v-singak\documents\projects\plottr\plottr\plottr\plot\mpl.py", line 1198, in _colorplot2d
    self.data.label(zname)))
  File "c:\users\v-singak\documents\projects\plottr\plottr\plottr\plot\mpl.py", line 238, in colorplot2d
    x, y, z = num.crop2d(x, y, z)
  File "c:\users\v-singak\documents\projects\plottr\plottr\plottr\utils\num.py", line 392, in crop2d
    ret = [crop2d_from_xy(a, xs, ys) for a in allarrs]
  File "c:\users\v-singak\documents\projects\plottr\plottr\plottr\utils\num.py", line 392, in <listcomp>
    ret = [crop2d_from_xy(a, xs, ys) for a in allarrs]
  File "c:\users\v-singak\documents\projects\plottr\plottr\plottr\utils\num.py", line 373, in crop2d_from_xy
    a = np.delete(a, ys, axis=1)
  File "<__array_function__ internals>", line 6, in delete
  File "C:\Users\v-singak\Miniconda3\envs\qcodes_plottr_dev\lib\site-packages\numpy\lib\function_base.py", line 4480, in delete
    keep[obj,] = False
IndexError: arrays used as indices must be of integer (or boolean) type
```

A possible solution is to cast `ys` as `int` before passing to `a = np.delete(a, ys, axis=1)`

Steps to reproduce:
Run plottr for live plotting a qcodes measurement with numpy version 1.20.3 in environment.

Expected behaviour:
Plottr runs smoothly without any errors on consol.

Observed behaviour:
The measurement runs fine but on console where the plottr-inspectr is initialized, above error occurs.

**Comment by jenshnielsen** [comment]
I cannot reproduce the issue. As far as I can see from the code in `colorplot2d` we should only call crop2d if some of the x or y values are None (Since the nan case is handled above by interpolation). Can you give some more detail about how this was triggered

**Comment by Akshita07** [comment]
This error is seen when live plotting with plottr is run in combination of do2d function.

Steps tp reproduce:
1. Setup a measurement with dummy `dac`  and `dmm` as follows: 
```python
from qcodes import initialise_or_create_database_at
from qcodes.tests.instrument_mocks import DummyInstrument, DummyInstrumentWithMeasurement
from qcodes.utils.dataset.doNd import do2d

dac = DummyInstrument('dac', gates=['ch1', 'ch2'])

dmm = DummyInstrumentWithMeasurement('dmm', setter_instr=dac) 

initialise_or_create_database_at("./experiments.db")

do2d(dac.ch1, 0, 100, 10, 1, dac.ch2, 0, 100, 10, 1, dmm.v1)
```
2. Before running do2d function initialize plottr-inspectr in another console (qcodes and plottr are installed in the same environment). Refreshrate set at 0.4s and autoplot new checked.

This gives the error mentioned above in the console where plottr inspectr is initialized

**Comment by jenshnielsen** [comment]
I think the problem is in joint_crop2d_rows_cols

If list(set(xs) or list(set(ys) is empty this will try to do np.array([]) which will create an array of floats. something like 

```python
def joint_crop2d_rows_cols(*arr: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """
    Get idxs where full rows/cols are invalid in any of the input arrays.
    Uses ``crop2d_rows_cols`` for each, then joins indices.

    :param arr: input 2d arrays.
    :return: x/y indices with invalid rows/cols.
    """
    xs = []
    ys = []

    for a in arr:
        _x, _y = crop2d_rows_cols(a)
        xs += _x.tolist()
        ys += _y.tolist()

    newxs = np.array(list(set(xs)), dtype=np.int64)
    newys = np.array(list(set(ys)), dtype=np.int64)
    return newxs, newys
```

Will fix that thou I am then getting another error when the code tries doing a scatterplot 
```ValueError: RGBA values should be within 0-1 range```
