### ISSUE TITLE
design plot server functionality

### ISSUE THREAD

**Issue by wpfff** [toolsforexperiments/plottr#204]
idea: have a server running, and we can just 'push' data into it (like the original version of plottr).
Need to come up with a design for:
- how much control does the client get?
- should we interface it with any of the other tools (like monitr)?

**Comment by marcosfrenkel** [comment]
because of the app manager, each autoplot window from monitr is being launched with a server, however this only happens when the window is being launched from mointr itself. This server is able to talk with the app though, is that enough to consider that closed?
