### ISSUE TITLE
plottr-inspectr incompatible with Python 3.10

### ISSUE THREAD

**Issue by cprosko** [toolsforexperiments/plottr#256]
Creating a fresh Python 3.10 environment, installing plottr, then attempting to run `plottr-inspectr` yields the error:
![image](https://user-images.githubusercontent.com/39212666/148965535-a9582dab-aeae-442a-a72d-13709bd03ae2.png)

Steps to reproduce:

1. Open an Anaconda terminal and run `conda create -n <env_name> python=3.10`.
2. Run `pip install pyqt5` in the new environment.
3. Run `pip install qcodes`.
4. Run `pip install plottr`.
5. Run `plottr-inspectr` to produce the error.

Note that repeating the above steps with `python=3.9` instead of `3.10` does not lead to any error.

**Comment by jenshnielsen** [comment]
Could you check if https://github.com/toolsforexperiments/plottr/pull/257 solves the issue?

**Comment by cprosko** [comment]
Sorry, I'm a bit late. You worked too fast 😄 yes that fixed the issue, thank you.

**Comment by jenshnielsen** [comment]
Thanks, I will push out a new release tomorrow with the fix
