### ISSUE TITLE
Auto Plot New Opens All DB Runs

### ISSUE THREAD

**Issue by cprosko** [toolsforexperiments/plottr#262]
I noticed this is the same as an old issue which was closed: #49 but the issue persists for me with plottr version 0.9.1:

Opening a .db file with plottr-inspectr _after_ having ticked 'auto-plot new' causes all measurement runs from that database file to be opened. I believe this is undesirable behavior since .db files can easily exceed 100 measurements.

**Comment by jenshnielsen** [comment]
I am able to reproduce this but only if both refresh interval is set to none zero and autoplot new is toggled

**Comment by jenshnielsen** [comment]
This happens if the refresh interval is set low. I think what happens is that while the first load correctly excludes plotting of everything the first refresh is triggered before this is done. That then triggers a replot of every thing
