### ISSUE TITLE
Using a  standards compliant date format.

### ISSUE THREAD

**Issue by GeneralSarsby** [toolsforexperiments/plottr#3]
plottr/plottr/plottr.py  line 38:
   TIMEFMT = "[%Y/%m/%d %H:%M:%S]"
is not a standard date format. 
I think it should be:
   TIMEFMT = "[%Y-%m-%d %H:%M:%S]"
so that it is both a valid [RFC2822](https://tools.ietf.org/html/rfc2822#section-3.3) and valid [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601). 

Just a small change to be standards compliant

**Comment by wpfff** [comment]
agreed, fixed :)
