### ISSUE TITLE
Fail with subscription at qcodes

### ISSUE THREAD

**Issue by 4mokie** [toolsforexperiments/plottr#36]
Tried to integrate plottr (v.0.1.0) to qcodes (v.0.1.11) according to [this](http://qcodes.github.io/Qcodes/examples/plotting/live_plotting.html), but it looks like there is some module structure mismatch (?) between them.  According to default qcodestc.json, qcodes tries to call `plottr.qcodes_dataset.QcodesDatasetSubscriber`, but (1) currently `qcodes_dataset.py` is located under `plottr/data` folder, and (2) I'm not able to find  `QcodesDatasetSubscriber` anywhere. So the subscription to the plottr has been failed.

I'm new in the field, so any help would be appreciated

**Comment by wpfff** [comment]
Hi @4mokie, we've recently changed the way plottr works with qcodes datasets. An important change was that we don't use the subscriber in the most recent versions of plottr anymore, but we rather monitor the qcodes .db file directly. The info you linked seems to be outdated, i'll get in touch with the qcodes developers about that.

For an up-to-date quickstart on how to use plottr, please see the quickstart on the repository homepage, and the example notebooks in doc/examples/.

You can, however, still get the 'old' behavior to work by installing from the ``plottr-original`` branch. I wouldn't recommend that in the long term, though.

Let me know if that works for you!

**Comment by 4mokie** [comment]
Thanks @wpfff , I've successfully launched inspectr tool, but I still confused with that 'live plotting' option. I added `meas.write_period` parameter in my code and checked "Auto-plot new" box in inspectr, but during the measurement the plottr window is not responding, so I cannot see graph until meas is done.  I even tried to add 1 s delay between experimental points, no effects. From [this notebook](https://github.com/kouwenhovenlab/plottr/blob/master/doc/examples/Live%20plotting%20qcodes%20data.ipynb) it's not clear for me how to handle this. 
Thanks!

**Comment by wpfff** [comment]
did you launch the inspectr process in a separate console? the behavior you describe is the one i'd expect when running it from the same notebook as the measurement. can you maybe share the code you used?

**Comment by 4mokie** [comment]
Hmm, I'm not pretty familiar with those consoles, so I need some time to read about it.  But usually I use spyder to run my code. And yes,  I launched plottr and measurement in there. Is it more correct to use jupyter notebooks for that?

**Comment by 4mokie** [comment]
Ok, I launched the inspectr for separate console and now it works properly, thanks!

**Comment by wpfff** [comment]
great, good to hear it works!  :)
