### ISSUE TITLE
Failing to run plottr-inspectr with AttributeError: module 'h5py' has no attribute 'File'

### ISSUE THREAD

**Issue by jpdehollain** [toolsforexperiments/plottr#366]
I just installed plottr using conda, when I try to run plottr-inspectr I get the error mentioned in the title. See screenshot of the error below:
![image](https://user-images.githubusercontent.com/6849791/216512693-f75787bd-3356-45d3-9a90-16da7ea36c11.png)

**Comment by jpdehollain** [comment]
Never mind, I had a mix-up with my installs. After reinstalling on a new env everything worked fine.

**Comment by abel-hugot** [comment]
Hi!
What exactly was the problem with your installs? I get the same error in a conda environment with only qcodes and plottr installed.
I tried reinstalling in new environments like you did but that does not seem to fix the issue.

**Comment by jpdehollain** [comment]
> Hi! What exactly was the problem with your installs? I get the same error in a conda environment with only qcodes and plottr installed. I tried reinstalling in new environments like you did but that does not seem to fix the issue.

I think the my original problem was that I had already installed `plottr` with `pip` and had forgotten, then I installed it again with `conda`.
In any case, after starting from a clean environment, I ran `pip install qcodes`, then `pip install plottr[PyQt5]`, and then it worked fine.
