### ISSUE TITLE
Rescale color map

### ISSUE THREAD

**Issue by jdwatson** [toolsforexperiments/plottr#37]
One issue that crops up fairly often with lockin measurements (though other measurements probably suffer from similar issues) is that a transient completely ruins the color scale and leaves 99% of the data at one end of the color bar.  It would be nice to be able to set the range of the color bar manually in the GUI and have the color scale in the plot change accordingly.

**Comment by wpfff** [comment]
good suggestion! i had put that aside for now, since i always was under the impression that you can that alter that kind of stuff with the matplotlib menu already. turns out that's not true for color bars :P

I'll try to implement that in the next days!

**Comment by astafan8** [comment]
@wpfff, you might want to have a look and/or reuse the following code that is used in `plot_by_id` in `qcodes`, [see these kwargs of `plot_by_id`](https://github.com/QCoDeS/Qcodes/blob/1c14781a7c7239140125c5bb3047a1bcb4a1b674/qcodes/dataset/plotting.py#L127), and [the following functions which manage the color scale stuff](https://github.com/QCoDeS/Qcodes/blob/master/qcodes/utils/plotting.py), and [the example notebook that explains what's going on](http://qcodes.github.io/Qcodes/examples/plotting/auto_color_scale.html). This will hopefully save you some development time (btw, credits to Dominik Vogel for implementing those functions).

**Comment by wpfff** [comment]
thanks, that's pretty useful! i have some similar tool lying around somewhere, but this looks a bit neater.

i'm actually thinking of making adjustable scales with input widgets, or maybe even something like this:
http://www.ster.kuleuven.be/~pieterd/python/html/plotting/interactive_colorbar.html

**Comment by marcosfrenkel** [comment]
@wpfff has this been solved by our current colorbar adjustment in the pyqtgraph backend?
