### ISSUE TITLE
crash when clicking on parameter name [in plotting window]

### ISSUE THREAD

**Issue by vhartong** [toolsforexperiments/plottr#47]
Everything is running smoothly, dual plotting is possible. 
But when clicking on the parameter name, it causes a crash. 
Only error notification is: 
> TypeError: native Qt signal is not callable

**Comment by wpfff** [comment]
I actually tracked that one down recently :)
i'll merge a fix shortly (i hope)

**Comment by wpfff** [comment]
should be fixed now. let me know if if re-appears.
