### ISSUE TITLE
Request: In plot-window button for "Tight layout" and "Copy to clipboard"

### ISSUE THREAD

**Issue by vhartong** [toolsforexperiments/plottr#50]
To generate a quick overview of all measurement data, it has become common practice to copy paste the graphs in to the onenote. Now this is done by selecting a windows over the plots, which is not so practical. 
So with this, could it be possible add two buttons below the graph showing one for a tight layout and one to copy the plot to the clipboard. 
Thanks in forward!

**Comment by wpfff** [comment]
Hey @vhartong -- i've added the tight-layout one just now (rest following very soon).
LMK if that is how you had it in mind!

**Comment by vhartong** [comment]
The copy button has appeared, but somehow there is something odd: 
The graph in the clipboard is paste-able to paint, but unpaste-able to onenote. When pasting the graph in paint, copying to clipboard again and then pasting in onenote seems to work.

**Comment by wpfff** [comment]
it's indeed odd -- it actually depends also on the version of onenote i noticed. ppt works, on the other hand (at least for me). i'll have a look...

**Comment by wpfff** [comment]
hey @vhartong -- let me know if it works better now.
I've tinkered with some settings, for me c/p works now fine to paste into onenote (office version), powerpoint, and onenote in the browser. for some reason i cannot paste into the end user version of onenote, but hopefully that shouldn't matter so much for us?

**Comment by vhartong** [comment]
Thanks for the update! I can confirm that copy/pasting to OneNote 2016 (Office version) works and to OneNote (end user version?) does not seem to work. 
Since OneNote 2016 works, this seems to do the job that was requested! Thanks! 👍
