### ISSUE TITLE
Label plot axis with parameter label

### ISSUE THREAD

**Issue by neildick** [toolsforexperiments/plottr#69]
Hey @wpfff 

Currently the plot axes are labelled with '{param_name}_{unit}'. This is a bit different to `plot_by_id` which will use the parameter label. This is kind of nice when you use a station yaml file to relabel things from 'ch2.source_voltage' to 'Gate Voltage' or similar.

Would this be an easy thing to add?

**Comment by wpfff** [comment]
hey @neildick -- that wouldn't be too hard i think. We'll have to add some additional metadata to the data format that's used internally, and then use that, if available, in the actual plotting. I'll look at what needs to happen for that (but will take a few weeks, I'll be travelling for most of September).

**Comment by jenshnielsen** [comment]
fixed by https://github.com/toolsforexperiments/plottr/pull/150
