### ISSUE TITLE
plottr crashes while plotting a measurement that was recorded without a station defined

### ISSUE THREAD

**Issue by simonzihlmann** [toolsforexperiments/plottr#81]
plottr crashes when one tries to plot a measurement that was recorded without prior definition of a station in qcodes. Once a station is defined, plottr can plot the new measurements as usual.
Here is a sample code that first creates a measurement without having defined a station (id1) and a second one after defining a station (id2). 

```
from functools import partial
import os

import numpy as np

from qcodes.dataset.sqlite.database import initialise_or_create_database_at
from qcodes.dataset.experiment_container import load_or_create_experiment
from qcodes.tests.instrument_mocks import DummyInstrument
from qcodes.dataset.measurements import Measurement
from qcodes.dataset.plotting import plot_dataset

from qcodes import Station

tutorial_db_path = os.path.join(os.getcwd(), 'plottr_crash.db')
initialise_or_create_database_at(tutorial_db_path)
load_or_create_experiment("plottr", sample_name="no sample")

# preparatory mocking of physical setup
dac = DummyInstrument('dac', gates=['ch1', 'ch2'])
dmm = DummyInstrument('dmm', gates=['v1', 'v2'])

def gauss_model(x0: float, y0: float, sigma: float, noise: float=0.0005):
    """
    Returns a generator sampling a gaussian. The gaussian is
    normalised such that its maximal value is simply 1
    """
    while True:
        (x, y) = yield
        model = np.exp(-((x0-x)**2+(y0-y)**2)/2/sigma**2)*np.exp(2*sigma**2)
        noise = np.random.randn()*noise
        yield model + noise

# and finally wire up the dmm v1 to "measure" the gaussian

gauss = gauss_model(0.1, 0.2, 0.25)
next(gauss)

def measure_gauss(dac):
    val = gauss.send((dac.ch1.get(), dac.ch2.get()))
    next(gauss)
    return val

dmm.v1.get = partial(measure_gauss, dac)

def do1d(param_set, start, stop, num_points, delay, *param_meas):
    meas = Measurement()
    meas.register_parameter(param_set)  # register the first independent parameter
    output = []
    param_set.post_delay = delay
    # do1D enforces a simple relationship between measured parameters
    # and set parameters. For anything more complicated this should be reimplemented from scratch
    for parameter in param_meas:
        meas.register_parameter(parameter, setpoints=(param_set,))
        output.append([parameter, None])

    with meas.run() as datasaver:
        for set_point in np.linspace(start, stop, num_points):
            param_set.set(set_point)
            for i, parameter in enumerate(param_meas):
                output[i][1] = parameter.get()
            datasaver.add_result((param_set, set_point),
                                 *output)
    dataset = datasaver.dataset  # convenient to have for plotting
    return dataset

dataset = do1d(dac.ch1, 0, 1, 10, 0.01, dmm.v1, dmm.v2)

# Add all instruments to the station
station = Station(dac, dmm)

dataset = do1d(dac.ch1, 0, 1, 10, 0.01, dmm.v1, dmm.v2)
```
Plottr crashes with the following output on the console:

> (qcodes) E:\>python .\plottr\apps\inspectr.py
> Traceback (most recent call last):
>   File "e:\plottr\plottr\apps\inspectr.py", line 438, in plotRun
>     fc, win = autoplotQcodesDataset(pathAndId=(self.filepath, runId))
>   File "e:\plottr\plottr\apps\autoplot.py", line 253, in autoplotQcodesDataset
>     win = QCAutoPlotMainWindow(fc, pathAndId=pathAndId)
>   File "e:\plottr\plottr\apps\autoplot.py", line 229, in __init__
>     self.snapshotWidget.loadSnapshot(self.loaderNode.dataSnapshot)
>   File "e:\plottr\plottr\gui\widgets.py", line 150, in loadSnapshot
>     items = dictToTreeWidgetItems(snapshotDict)
>   File "e:\plottr\plottr\gui\widgets.py", line 163, in dictToTreeWidgetItems
>     for k, v in d.items():
> AttributeError: 'NoneType' object has no attribute 'items'

Inspecting the database:
![inspector](https://user-images.githubusercontent.com/46719478/74260896-9abf8880-4cfa-11ea-80fd-984432edf0a3.PNG)

Trying to plot measurement 1 (id1):
![id1](https://user-images.githubusercontent.com/46719478/74260901-9d21e280-4cfa-11ea-890a-5914d6b50b79.PNG)

Plotting measurement 2 (id2):
![id2](https://user-images.githubusercontent.com/46719478/74260904-9e530f80-4cfa-11ea-94b9-0dcebad247fa.PNG)

**Comment by astafan8** [comment]
allow me to quickly suggest the fix (feel free to try it and if it works submit a PR to this repo).

as per [type annotation of `DataSet.snapshot` in qcodes](https://github.com/QCoDeS/Qcodes/blob/6b836f7997e7670332f9544725396840a1df7bbb/qcodes/dataset/data_set.py#L329) snapshot can be `None`. So, `plottr` needs to account for that. And it can do so here:

https://github.com/data-plottr/plottr/blob/de2fb64e862f1edf47d64ff5c6a78ec0a2774bb6/plottr/gui/widgets.py#L145-L152

This method should have the following signature:
```python
def loadSnapshot(self, snapshotDict: Optional[dict]):
```
where `from typing import Optional`, and the body should have the check for `None` before rendeding, for example like this:
```python
def loadSnapshot(self, snapshotDict: Optional[dict]):
        """
        Loads a qcodes DataSet snapshot in the tree view
        """
        self.clear()

        if snapshotDict is None:
            return

        items = dictToTreeWidgetItems(snapshotDict)
        # the rest of the method unchanged
```
