### ISSUE TITLE
Y-axis inverted in image-mode

### ISSUE THREAD

**Issue by jjwesd** [toolsforexperiments/plottr#87]
Just trying the latest version. 
- When plotting with the default image mode the y-axis is inverted
![image](https://user-images.githubusercontent.com/8937555/79553392-b3527300-809c-11ea-8a99-d32a1fd2c888.png)
Switching to the colormesh plot fixes this:
![image](https://user-images.githubusercontent.com/8937555/79553434-c5341600-809c-11ea-80d2-25cb9677b249.png)

**Comment by wpfff** [comment]
interesting :)
it looks like this is because you're measuring by sweeping down the voltage which is a case i probably overlooked :P 
will take a look today.

**Comment by wpfff** [comment]
@GitJaap should be fixed now - works fine in my tests. LMK if you agree.

**Comment by jjwesd** [comment]
thanks! i agree
